// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: assistant/v1/message.proto

package assistantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role indicates the role of the message sender.
type Message_Role int32

const (
	Message_ROLE_UNSPECIFIED Message_Role = 0
	Message_ROLE_USER        Message_Role = 1
	Message_ROLE_ASSISTANT   Message_Role = 2
)

// Enum value maps for Message_Role.
var (
	Message_Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_ASSISTANT",
	}
	Message_Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_ASSISTANT":   2,
	}
)

func (x Message_Role) Enum() *Message_Role {
	p := new(Message_Role)
	*p = x
	return p
}

func (x Message_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_assistant_v1_message_proto_enumTypes[0].Descriptor()
}

func (Message_Role) Type() protoreflect.EnumType {
	return &file_assistant_v1_message_proto_enumTypes[0]
}

func (x Message_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Role.Descriptor instead.
func (Message_Role) EnumDescriptor() ([]byte, []int) {
	return file_assistant_v1_message_proto_rawDescGZIP(), []int{0, 0}
}

// Message represents a single message in the chat session.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The role of the message sender.
	Role Message_Role `protobuf:"varint,1,opt,name=role,proto3,enum=assistant.v1.Message_Role" json:"role,omitempty"`
	// Contents of the message which can include various types.
	Contents      []*MessageContent `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_assistant_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_assistant_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() Message_Role {
	if x != nil {
		return x.Role
	}
	return Message_ROLE_UNSPECIFIED
}

func (x *Message) GetContents() []*MessageContent {
	if x != nil {
		return x.Contents
	}
	return nil
}

// MessageContent supports different types of content in a message.
type MessageContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*MessageContent_Text
	//	*MessageContent_Image
	//	*MessageContent_Attachment
	Content       isMessageContent_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_assistant_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_assistant_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageContent) GetContent() isMessageContent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MessageContent) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Content.(*MessageContent_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *MessageContent) GetImage() *URLImageContent {
	if x != nil {
		if x, ok := x.Content.(*MessageContent_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *MessageContent) GetAttachment() *AttachmentContent {
	if x != nil {
		if x, ok := x.Content.(*MessageContent_Attachment); ok {
			return x.Attachment
		}
	}
	return nil
}

type isMessageContent_Content interface {
	isMessageContent_Content()
}

type MessageContent_Text struct {
	// Text content.
	Text *TextContent `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type MessageContent_Image struct {
	// Image content represented by a URL.
	Image *URLImageContent `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type MessageContent_Attachment struct {
	// Attachment content with name, syntax, and content.
	Attachment *AttachmentContent `protobuf:"bytes,3,opt,name=attachment,proto3,oneof"` // Future content types can be added here.
}

func (*MessageContent_Text) isMessageContent_Content() {}

func (*MessageContent_Image) isMessageContent_Content() {}

func (*MessageContent_Attachment) isMessageContent_Content() {}

// TextContent wraps a piece of text.
type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_assistant_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_assistant_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// URLImageContent holds the URL of an image.
type URLImageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLImageContent) Reset() {
	*x = URLImageContent{}
	mi := &file_assistant_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLImageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLImageContent) ProtoMessage() {}

func (x *URLImageContent) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLImageContent.ProtoReflect.Descriptor instead.
func (*URLImageContent) Descriptor() ([]byte, []int) {
	return file_assistant_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *URLImageContent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// AttachmentContent represents an attachment with name, syntax highlighting, and content.
type AttachmentContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the attachment.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Syntax highlighting information (e.g., "go", "python", etc.).
	Syntax string `protobuf:"bytes,2,opt,name=syntax,proto3" json:"syntax,omitempty"`
	// The actual content of the attachment.
	Content       []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentContent) Reset() {
	*x = AttachmentContent{}
	mi := &file_assistant_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentContent) ProtoMessage() {}

func (x *AttachmentContent) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentContent.ProtoReflect.Descriptor instead.
func (*AttachmentContent) Descriptor() ([]byte, []int) {
	return file_assistant_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *AttachmentContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttachmentContent) GetSyntax() string {
	if x != nil {
		return x.Syntax
	}
	return ""
}

func (x *AttachmentContent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_assistant_v1_message_proto protoreflect.FileDescriptor

const file_assistant_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1aassistant/v1/message.proto\x12\fassistant.v1\"\xb4\x01\n" +
	"\aMessage\x12.\n" +
	"\x04role\x18\x01 \x01(\x0e2\x1a.assistant.v1.Message.RoleR\x04role\x128\n" +
	"\bcontents\x18\x02 \x03(\v2\x1c.assistant.v1.MessageContentR\bcontents\"?\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x12\n" +
	"\x0eROLE_ASSISTANT\x10\x02\"\xc6\x01\n" +
	"\x0eMessageContent\x12/\n" +
	"\x04text\x18\x01 \x01(\v2\x19.assistant.v1.TextContentH\x00R\x04text\x125\n" +
	"\x05image\x18\x02 \x01(\v2\x1d.assistant.v1.URLImageContentH\x00R\x05image\x12A\n" +
	"\n" +
	"attachment\x18\x03 \x01(\v2\x1f.assistant.v1.AttachmentContentH\x00R\n" +
	"attachmentB\t\n" +
	"\acontent\"!\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"#\n" +
	"\x0fURLImageContent\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"Y\n" +
	"\x11AttachmentContent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06syntax\x18\x02 \x01(\tR\x06syntax\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontentB\xaa\x01\n" +
	"\x10com.assistant.v1B\fMessageProtoH\x02P\x01Z5micheam.com/aico/internal/pb/assistant/v1;assistantv1\xa2\x02\x03AXX\xaa\x02\fAssistant.V1\xca\x02\fAssistant\\V1\xe2\x02\x18Assistant\\V1\\GPBMetadata\xea\x02\rAssistant::V1b\x06proto3"

var (
	file_assistant_v1_message_proto_rawDescOnce sync.Once
	file_assistant_v1_message_proto_rawDescData []byte
)

func file_assistant_v1_message_proto_rawDescGZIP() []byte {
	file_assistant_v1_message_proto_rawDescOnce.Do(func() {
		file_assistant_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assistant_v1_message_proto_rawDesc), len(file_assistant_v1_message_proto_rawDesc)))
	})
	return file_assistant_v1_message_proto_rawDescData
}

var file_assistant_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_assistant_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_assistant_v1_message_proto_goTypes = []any{
	(Message_Role)(0),         // 0: assistant.v1.Message.Role
	(*Message)(nil),           // 1: assistant.v1.Message
	(*MessageContent)(nil),    // 2: assistant.v1.MessageContent
	(*TextContent)(nil),       // 3: assistant.v1.TextContent
	(*URLImageContent)(nil),   // 4: assistant.v1.URLImageContent
	(*AttachmentContent)(nil), // 5: assistant.v1.AttachmentContent
}
var file_assistant_v1_message_proto_depIdxs = []int32{
	0, // 0: assistant.v1.Message.role:type_name -> assistant.v1.Message.Role
	2, // 1: assistant.v1.Message.contents:type_name -> assistant.v1.MessageContent
	3, // 2: assistant.v1.MessageContent.text:type_name -> assistant.v1.TextContent
	4, // 3: assistant.v1.MessageContent.image:type_name -> assistant.v1.URLImageContent
	5, // 4: assistant.v1.MessageContent.attachment:type_name -> assistant.v1.AttachmentContent
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_assistant_v1_message_proto_init() }
func file_assistant_v1_message_proto_init() {
	if File_assistant_v1_message_proto != nil {
		return
	}
	file_assistant_v1_message_proto_msgTypes[1].OneofWrappers = []any{
		(*MessageContent_Text)(nil),
		(*MessageContent_Image)(nil),
		(*MessageContent_Attachment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assistant_v1_message_proto_rawDesc), len(file_assistant_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assistant_v1_message_proto_goTypes,
		DependencyIndexes: file_assistant_v1_message_proto_depIdxs,
		EnumInfos:         file_assistant_v1_message_proto_enumTypes,
		MessageInfos:      file_assistant_v1_message_proto_msgTypes,
	}.Build()
	File_assistant_v1_message_proto = out.File
	file_assistant_v1_message_proto_goTypes = nil
	file_assistant_v1_message_proto_depIdxs = nil
}
