// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: assistant/v1/session.proto

package assistantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatSession represents a chat session.
type ChatSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the session.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Timestamp when the session was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// System instruction applied to the session (if any).
	SystemInstruction *TextContent `protobuf:"bytes,3,opt,name=system_instruction,json=systemInstruction,proto3" json:"system_instruction,omitempty"`
	// History of chat messages including user and assistant messages.
	History       []*Message `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSession) Reset() {
	*x = ChatSession{}
	mi := &file_assistant_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSession) ProtoMessage() {}

func (x *ChatSession) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSession.ProtoReflect.Descriptor instead.
func (*ChatSession) Descriptor() ([]byte, []int) {
	return file_assistant_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *ChatSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatSession) GetSystemInstruction() *TextContent {
	if x != nil {
		return x.SystemInstruction
	}
	return nil
}

func (x *ChatSession) GetHistory() []*Message {
	if x != nil {
		return x.History
	}
	return nil
}

var File_assistant_v1_session_proto protoreflect.FileDescriptor

const file_assistant_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1aassistant/v1/session.proto\x12\fassistant.v1\x1a\x1aassistant/v1/message.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\vChatSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12H\n" +
	"\x12system_instruction\x18\x03 \x01(\v2\x19.assistant.v1.TextContentR\x11systemInstruction\x12/\n" +
	"\ahistory\x18\x04 \x03(\v2\x15.assistant.v1.MessageR\ahistoryB\xaa\x01\n" +
	"\x10com.assistant.v1B\fSessionProtoH\x02P\x01Z5micheam.com/aico/internal/pb/assistant/v1;assistantv1\xa2\x02\x03AXX\xaa\x02\fAssistant.V1\xca\x02\fAssistant\\V1\xe2\x02\x18Assistant\\V1\\GPBMetadata\xea\x02\rAssistant::V1b\x06proto3"

var (
	file_assistant_v1_session_proto_rawDescOnce sync.Once
	file_assistant_v1_session_proto_rawDescData []byte
)

func file_assistant_v1_session_proto_rawDescGZIP() []byte {
	file_assistant_v1_session_proto_rawDescOnce.Do(func() {
		file_assistant_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assistant_v1_session_proto_rawDesc), len(file_assistant_v1_session_proto_rawDesc)))
	})
	return file_assistant_v1_session_proto_rawDescData
}

var file_assistant_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_assistant_v1_session_proto_goTypes = []any{
	(*ChatSession)(nil),           // 0: assistant.v1.ChatSession
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*TextContent)(nil),           // 2: assistant.v1.TextContent
	(*Message)(nil),               // 3: assistant.v1.Message
}
var file_assistant_v1_session_proto_depIdxs = []int32{
	1, // 0: assistant.v1.ChatSession.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: assistant.v1.ChatSession.system_instruction:type_name -> assistant.v1.TextContent
	3, // 2: assistant.v1.ChatSession.history:type_name -> assistant.v1.Message
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_assistant_v1_session_proto_init() }
func file_assistant_v1_session_proto_init() {
	if File_assistant_v1_session_proto != nil {
		return
	}
	file_assistant_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assistant_v1_session_proto_rawDesc), len(file_assistant_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assistant_v1_session_proto_goTypes,
		DependencyIndexes: file_assistant_v1_session_proto_depIdxs,
		MessageInfos:      file_assistant_v1_session_proto_msgTypes,
	}.Build()
	File_assistant_v1_session_proto = out.File
	file_assistant_v1_session_proto_goTypes = nil
	file_assistant_v1_session_proto_depIdxs = nil
}
